### ISSUE TITLE
Feature - Add Screenshot 

### ISSUE THREAD

**Issue by unl1k3ly** [mazen160/xless#5]
Hi mate, such a nice project. Thank you.

How hard would that be to add a screenshot of the browser when js is triggered ?

Cherrs

**Comment by mazen160** [comment]
Hi @unl1k3ly!

The issue is, uploading a screenshot requires a place to store images, such as an S3 bucket for example.

The Slack incoming web hook does not allow uploading files to Slack as far as I know.

The uploading part is easy. The difficult part is where to store while using a serverless environment.

**Comment by unl1k3ly** [comment]
Sorry for such delay response mate... Would be possible to use an aws s3 integration once we provide keys ? this would be so mad! cheers

**Comment by mazen160** [comment]
Hi @unl1k3ly 

This will be an excellent addition!

Let's keep this ticket open. It will be great if anyone would like to contribute with this addition.

Best regards,
Mazin

**Comment by phspade** [comment]
Hmm.. maybe put some optional to place their AWS key and secret to the code. if they don't provide the AWS key and secret then no screenshot but if they do then screenshot.

**Comment by 0xspade** [comment]
Hi @mazen160,

Let's place a $50 bounty on this feature for those willing to create the screenshot feature in this project.

**Comment by rotemreiss** [comment]
> Hi @mazen160,
> 
> Let's place a $50 bounty on this feature for those willing to create the screenshot feature in this project.

Bring me the money ;)

I had to do it for all of us. I love xless, but this is a major feature which is missing!

**Comment by 0xspade** [comment]
Oh yeah!

Let me know if you push the updates already 👍

**Comment by 0xspade** [comment]
Hey @rotemreiss,

Didn't notice your push there. DM me twitter.com/0xspade 👍

**Comment by rotemreiss** [comment]
> Hey @rotemreiss,
> 
> Didn't notice your push there. DM me twitter.com/0xspade 👍

You can use my fork in the meanwhile if you want or just wait until @mazen160 will do the merge here.
BTW you are blocked for DM, you are welcome to [ping me](https://twitter.com/2RS3C)

**Comment by 0xspade** [comment]
Check DM man 👍

**Comment by 0xspade** [comment]
100% working without error.

**Comment by mazen160** [comment]
Finally it's there :fire: :fire: 
Thank you @unl1k3ly for developing this awesome addition! and of course, thank you @0xspade for the bounty!
